---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    auto_tag: true
    context: .
    force_tag: true
    insecure: true
    registry: registry:5000
    repo: registry:5000/hopsoft/turbo_boost-commands
    use_cache: true
