---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    add_host: registry:5000
    context: .
    force_tag: true
    insecure: true
    registry: registry:5000
    repo: registry:5000/hopsoft/turbo_boost-commands
    tags: ci-${DRONE_COMMIT_SHA}
    use_cache: true
