---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    context: .
    tags:
      - hopsoft/turbo_boost-commands:ci-${DRONE_COMMIT_SHA}
    use_cache: true
