---
kind: pipeline
type: docker
name: default

workspace:
  path: /drone/src

volumes:
  - name: cache
    temp: {}

steps:
  - name: restore
    image: meltwater/drone-cache:v1
    settings:
      backend: filesystem
      restore: true
      archive_format: gzip
      filesystem_cache_root: /cache
      mount:
        - images
    volumes:
      - name: cache
        path: /cache

  - name: build
    image: plugins/docker
    settings:
      context: .
      tags: hopsoft/turbo_boost-commands:ci
      storage_path: /cache/images
      compress: true
      force_tag: true
      insecure: true
      use_cache: true
    volumes:
      - name: cache
        path: /cache

  - name: standardrb
    image: turbo_boost-commands:ci
    commands:
      - shopt -s globstar
      - bundle exec standardrb --format progress
    volumes:
      - name: cache
        path: /cache
