---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    auto_tag: true
    compress: true
    context: .
    force_tag: true
    insecure: true
    pull_image: true
    registry: http://registry:5000
    repo: hopsoft/turbo_boost-commands
    use_cache: true
