---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    context: .
    force_tag: true
    insecure: true
    registry: registry:5000
    repo: registry:5000/hopsoft/turbo_boost-commands
    storage_path: /cache
    tags: ci
    use_cache: true

- name: standardrb
  image: registry:5000/hopsoft/turbo_boost-commands:ci
  commands:
  - shopt -s globstar
  - bundle exec standardrb --format progress
