---
kind: pipeline
type: docker
name: default

steps:
  - name: restore-cache
    image: meltwater/drone-cache:v1
    settings:
      backend: filesystem
      restore: true
      archive_format: gzip
      filesystem_cache_root: /cache
      mount:
        - /mnt/external
    volumes:
      - name: cache
        path: /cache

  - name: build-image
    image: plugins/docker
    settings:
      context: .
      registry: registry:5000
      repo: registry:5000/hopsoft/turbo_boost-commands
      tags: ci-${DRONE_COMMIT_SHA}
      force_tag: true
      insecure: true
      use_cache: true

  - name: rebuild-cache
    image: meltwater/drone-cache:v1
    settings:
      backend: filesystem
      rebuild: true
      archive_format: gzip
      filesystem_cache_root: /cache
      mount:
        - /mnt/external
    volumes:
      - name: cache
        path: /cache

  - name: peek
    image: alpine
    commands:
      - apk update
      - apk add tree
      - tree /cache
    volumes:
      - name: cache
        path: /cache

  - name: prepare
    image: docker:24
    settings:
      commands:
        - echo "Hello World!"

  #- name: check-standardrb
    #image: hopsoft/turbo_boost-commands:ci-${DRONE_COMMIT_SHA}
    #pull: never
    #commands:
      #- shopt -s globstar
      #- bundle exec standardrb --format progress
    #volumes:
      #- name: docker
        #path: /var/lib/docker
