---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    context: .
    registry: registry
    repo: registry/hopsoft/turbo_boost-commands
    tags:
      - ci-${DRONE_COMMIT_SHA}
    use_cache: true
