---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    context: .
    insecure: true
    registry: http://registry:5000
    repo: registry:5000/hopsoft/turbo_boost-commands
    tags: ci-${DRONE_COMMIT_SHA}
    use_cache: true
