---
kind: pipeline
type: docker
name: default

steps:
  - name: restore-cache
    image: meltwater/drone-cache:v1
    settings:
      backend: filesystem
      restore: true
      archive_format: gzip
      filesystem_cache_root: /cache
      mount:
        - /mnt/external
        - /var/lib/docker
    volumes:
      - name: cache
        path: /cache
      - name: external
        path: /mnt/external

  - name: build-image
    image: plugins/docker
    settings:
      context: .
      registry: registry:5000
      repo: registry:5000/hopsoft/turbo_boost-commands
      tags: ci
      #tags: ci-${DRONE_COMMIT_SHA}
      compress: true
      force_tag: true
      insecure: true
      storage_path: /var/lib/docker
      use_cache: true


  - name: rebuild-cache
    image: meltwater/drone-cache:v1
    settings:
      backend: filesystem
      rebuild: true
      archive_format: gzip
      filesystem_cache_root: /cache
      mount:
        - /mnt/external
        - /var/lib/docker
    volumes:
      - name: cache
        path: /cache
      - name: external
        path: /mnt/external

  - name: peek
    image: alpine
    commands:
      - apk update
      - apk add tree
      - tree /cache
    volumes:
      - name: cache
        path: /cache
      - name: external
        path: /mnt/external

  - name: prepare
    image: docker:24-dind
    settings:
      commands:
        - docker run hello-world
    volumes:
      - name: external
        path: /mnt/external

  #- name: check-standardrb
    #image: hopsoft/turbo_boost-commands:ci-${DRONE_COMMIT_SHA}
    #pull: never
    #commands:
      #- shopt -s globstar
      #- bundle exec standardrb --format progress
    #volumes:
      #- name: docker
        #path: /var/lib/docker
