---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: docker:dind
  commands:
  - sleep 5 # give docker enough time to start
  - docker compose build

services:
- name: docker
  image: docker:dind
