---
kind: pipeline
type: docker
name: default

plugins:
  docker: {}

steps:
- name: build
  image: plugins/docker
  settings:
    context: .
    tags:
      - hopsoft/turbo_boost-commands:${DRONE_COMMIT_SHA}
