ruby_version: 2.7
format: progress
parallel: true

ignore:
  - test/dummy/bin/*
  - test/dummy/config/initializers/inspect_helpers.rb
  - test/dummy/db/schema.rb

Lint/RescueException:
  Enabled: false
