version: '3.9'

networks:
  primary:

volumes:
  external:

x-default-app: &default_app
  build: .
  image: hopsoft/turbo_boost-commands
  stdin_open: true
  tty: true
  environment:
    DATABASE_URL: sqlite3:///mnt/external/database/development.sqlite3
    GEM_HOME: /mnt/external/gems
    PLAYWRIGHT_BROWSERS_PATH: 0
    PLAYWRIGHT_CLI_EXECUTABLE_PATH: /app/node_modules/.bin/playwright
    RAILS_ENV: development
    RAILS_LOG_TO_STDOUT: true
    RAILS_SERVE_STATIC_FILES: true
    YARN_CACHE_FOLDER: /mnt/external/yarn/.cache
  networks:
    - primary
  volumes:
    - .:/app
    - external:/mnt/external

services:
  # ==========================================================================================================
  # Web - Runs the test/dummy Rails app
  # ==========================================================================================================
  web:
    <<: *default_app
    container_name: turbo_boost-commands-web
    ports:
      - 3000:3000
    command: bin/docker/run/local
    healthcheck:
      test:
        ['CMD', 'curl', '--silent', '--fail', 'http://localhost:3000/health']
      interval: 30s
      timeout: 30s
      retries: 10

  # ==========================================================================================================
  # ESBuild - Runs the esbuild watcher
  # ==========================================================================================================
  esbuild:
    <<: *default_app
    container_name: turbo_boost-commands-esbuild
    command: /bin/bash -c "yarn build:watch"
    depends_on:
      web:
        condition: service_healthy

  # ==========================================================================================================
  # Tailwind - Runs the Tailwind watcher
  # ==========================================================================================================
  tailwind:
    <<: *default_app
    container_name: turbo_boost-commands-tailwind
    working_dir: /app/test/dummy
    command: bin/rails tailwindcss:watch
    depends_on:
      web:
        condition: service_healthy
