# fly.toml app configuration file generated for turbo-boost-commands on 2023-05-23T22:00:07-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "turbo-boost-commands"
primary_region = "den"

[env]
  DATABASE_URL = "sqlite3:///mnt/external/database/development.sqlite3"
  RAILS_ENV = "development"
  RAILS_LOG_TO_STDOUT = "true"
  RAILS_MAX_THREADS = "6"
  RAILS_RELATIVE_URL_ROOT = "/@turbo-boost/commands"
  RAILS_SERVE_STATIC_FILES = "true"
  WEB_CONCURRENCY = "2"

[[mounts]]
  source = "turbo_boost_commands_volume"
  destination = "/mnt/external"

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false

[[statics]]
  guest_path = "/app"
  url_prefix = "/"
