networks:
  primary:

volumes:
  caddy_config:
  caddy_data:
  docker_registry_data:

services:
  "registry.local":
    image: registry:2
    container_name: registry
    networks:
      - primary
    restart: unless-stopped
    volumes:
      - docker_registry_data:/var/lib/registry
      - /home/docker/.config/drone/docker_registry_config.yml:/etc/docker/registry/config.yml

  drone_server:
    image: drone/drone:2
    container_name: drone-server
    depends_on:
      "registry.local":
        condition: service_started
    env_file: .env
    networks:
      - primary
    restart: unless-stopped
    healthcheck:
      test: wget --tries=1 -S -O /dev/null http://localhost:80 || exit 1
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 10s

  drone_runner:
    image: drone/drone-runner-docker:1
    container_name: drone-runner
    depends_on:
      "registry.local":
        condition: service_started
      drone_server:
        condition: service_healthy
    env_file: .env
    networks:
      - primary
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  caddy:
    image: caddy:2
    container_name: caddy
    depends_on:
      drone_server:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    networks:
      - primary
    restart: unless-stopped
    volumes:
      - /home/docker/.config/drone/Caddyfile:/etc/caddy/Caddyfile
      - caddy_config:/config
      - caddy_data:/data
