version: 0.1
http:
  addr: 0.0.0.0:5000
  secret: 35x03e9d593142529264643dc668d02b
log:
  accesslog:
    disabled: false
  level: debug
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
validation:
  manifests:
    urls:
      allow:
        - ^http://runner
        - ^http://server
