version: 0.1
http:
  secret: local-registry
log:
  level: debug
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
validation:
  manifests:
    urls:
      allow:
        - ^http?://([^/]+\.)*runner/
        - ^http?://([^/]+\.)*server/
