name: Prettier

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  prettier:
    name: Prettier Check Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          version: '20.x'
          cache: 'yarn'

      - name: Yarn install
        run: 'yarn install --frozen-lockfile'

      - name: Run Prettier
        run: 'yarn run prettier --check --fail-on-errors .'

