name: StandardRB

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  standard:
    name: StandardRB Check Action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.3']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run StandardRB
        run: bundle exec standardrb --format progress
