name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        ruby-version: ['2.7', '3.0', '3.1', '3.2', '3.3']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn

    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Yarn install
      run: yarn install --frozen-lockfile --network-concurrency=3

    - name: Install Playwright Browsers
      run: yarn playwright install

    - name: Install Playwright Dependencies
      run: yarn playwright install-deps

    - name: Run ruby tests
      run: bundle exec rake MINITEST_FAIL_FAST=true
